baseURL = "http://changkun.de/golang"
languageCode = "zh-cn"
title = "Go Under The Hood"
theme = "book"

[markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "vs"
    tabWidth = 4
[markup.goldmark.renderer]
    unsafe= true